### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{   "first_name": "John",
  	"email": "john@gmail.com",
  	"password": "John123!",
  	"confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1


### GET /users
GET http://localhost:8080/users HTTP/1.1


### GET /roles
GET http://localhost:8080/roles/ HTTP/1.1


### POST /roles
POST http://localhost:8080/roles HTTP/1.1
Content-Type: application/json

{
	"name": "Viewer",
	"permissions": ["9ebcde6b-eb39-47ee-9d88-a9d694f2a240"]
}

### PATCH /roles/:id
PATCH http://localhost:8080/roles/fba149ca-6168-4c38-8f96-635e134db423 HTTP/1.1
Content-Type: application/json

{
	"name": "Admin",
	"permissions": ["1f82ca3a-4f57-482d-aaeb-375f7f6d8cbc","33ef24ec-63ba-4cfa-9736-a0788382796d"]
}




### GET /permissions
GET http://localhost:8080/permissions 



### POST /permissions
POST http://localhost:8080/permissions HTTP/1.1
Content-Type: application/json

{
  	"name": "edit_permissions"
}

### PATCH /users/:id
PATCH http://localhost:8080/users/8afb3a65-4e80-492a-a83f-49d49103e68e HTTP/1.1
Content-Type: application/json

{   
	"role_id": "fba149ca-6168-4c38-8f96-635e134db423"

}

###

DELETE http://localhost:8080/roles/6ed573f0-be51-4702-bb4e-71a42a23ff34 HTTP/1.1